# Cloud Build configuration for automated deployment
# Usage: gcloud builds submit --config cloudbuild.yaml

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ocr-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'
      - '--max-instances'
      - '10'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ocr-api/ocr-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY
